
spring:
  datasource:
    url: jdbc:mysql://114.55.146.111:3306/lkdb-bak?useSSL=false&useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: dxrOTD!O2019
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    mongodb:
      host: 62.234.17.74
      port: 27017
      database: test

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.baomidou.mybatisplus.samples.quickstart.domain
  configuration:
    map-underscore-to-camel-case: true
    use-actual-param-name: true

#  打印sql执行语句
logging:
  level:
    com:
      baomidou:
        mybatisplus:
          samples:
            quickstart:
              mapper : debug
